### ISSUE TITLE
No generated migration

### ISSUE THREAD

**Issue by krzysieqq** [xtrinch/fcm-django#182]
Hi,
I'm using fcm_django in docker container with a non-root user. After build I always have a problem with makemigrations:

```
Migrations for 'fcm_django':
  /usr/local/lib/python3.9/site-packages/fcm_django/migrations/0007_alter_fcmdevice_id.py
    - Alter field id on fcmdevice
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 190, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 228, in write_migration_files
    with open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/fcm_django/migrations/0007_alter_fcmdevice_id.py'

```
Can you make migrations in fcm_django to resolve this problem?

**Comment by Andrew-Chen-Wang** [comment]
Oh crud... it's Django 3.2 thing where they auto field is defaulted to whatever you have
