### ISSUE TITLE
Cant install via requirements.txt

### ISSUE THREAD

**Issue by yandiro** [xtrinch/fcm-django#195]
Can't install it via requirements.txt in a docker.

```
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-psp4y8kj/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-psp4y8kj/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8__ugo4v
         cwd: /tmp/pip-install-psp4y8kj/grpcio/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-psp4y8kj/grpcio/setup.py", line 256, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-psp4y8kj/grpcio/setup.py", line 203, in check_linker_need_libatomic
        cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'],
      File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'c++'
``` 

When I remove the `fcm-django==1.0.8` line from requirements.txt, all works fine.

**Comment by yandiro** [comment]
Just in case someone bumps into this as well, this is how to solve it.

From this link (with more info):
https://github.com/grpc/grpc/issues/24556

add `apk add g++` to your docker file

**Comment by xtrinch** [comment]
Maybe it would be worth adding this to the documentation?

**Comment by yandiro** [comment]
I believe so, as a paragraph in the Docker section. May be useful!
